version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supportdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
  backend-api:
    build: ./apps/backend-api
    env_file: ./apps/backend-api/.env
    depends_on:
      - postgres
      - redis
      - ai-service
    ports:
      - "5000:5000"
  frontend:
    build: ./apps/frontend
    env_file: ./apps/frontend/.env
    depends_on:
      - backend-api
    ports:
      - "3000:80"
  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
volumes:
  pgdata:
